export const FETCH_VEHICLE_REQUEST = "FETCH_VEHICLE_REQUEST";
export const FETCH_VEHICLE_SUCCESS = "FETCH_VEHICLE_SUCCESS";
export const FETCH_VEHICLE_FAILIUR = "FETCH_VEHICLE_FAILIUR";

export const FETCH_VEHICLE_BY_ID_REQUEST = "FETCH_VEHICLE_BY_ID_REQUEST";
export const FETCH_VEHICLE_BY_ID_SUCCESS = "FETCH_VEHICLE_BY_ID_SUCCESS";
export const FETCH_VEHICLE_BY_ID_FAILIUR = "FETCH_VEHICLE_BY_ID_FAILIUR";

export const FETCH_SEARCH_VEHICLE_REQUEST = "FETCH_SEARCH_VEHICLE_REQUEST";
export const FETCH_SEARCH_VEHICLE_SUCCESS =
    "FETCH_SEARCH_VEHICLE_SUCCESS";
export const FETCH_SEARCH_VEHICLE_FAILIUR =
    "FETCH_SEARCH_VEHICLE_FAILIUR";

export const ADD_VEHICLE_REQUEST = "ADD_VEHICLE_REQUEST";
export const ADD_VEHICLE_SUCCESS = "ADD_VEHICLE_SUCCESS";
export const ADD_VEHICLE_FAILIUR = "ADD_VEHICLE_FAILIUR";

export const UPDATE_VEHICLE_REQUEST = "UPDATE_VEHICLE_REQUEST";
export const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS";
export const UPDATE_VEHICLE_FAILIUR = "UPDATE_VEHICLE_FAILIUR";

export const MARK_SOLD_VEHICLE_REQUEST = "MARK_SOLD_VEHICLE_REQUEST";
export const MARK_SOLD_VEHICLE_SUCCESS = "MARK_SOLD_VEHICLE_SUCCESS";
export const MARK_SOLD_VEHICLE_FAILIUR = "MARK_SOLD_VEHICLE_FAILIUR";

export const COUNT_VEHICLE_STATUS_REQUEST = "COUNT_VEHICLE_STATUS_REQUEST";
export const COUNT_VEHICLE_STATUS_SUCCESS = "COUNT_VEHICLE_STATUS_SUCCESS";
export const COUNT_VEHICLE_STATUS_FAILIUR = "COUNT_VEHICLE_STATUS_FAILIUR";
